### ISSUE TITLE
The system cannot find the path specified on compile

### ISSUE THREAD

**Issue by nmisolutions** [madskristensen/WebCompiler#158]
I'm using WebCompiler, it's a great extension for Visual Studio, however I recently stumbled on the issue that I couldn't resolve. It looks like the issue is somewhat computer specific because I tried to do the same on two other machines and couldn't reproduce the behavior. 
The problem is when on my machine try to compile project that has sass, less or coffeescript file in it, I receive "the system cannot find the path specified" error (in source column there is both IntelliSense and Build). 
Please note that I have both Visual Studio 2013 Professional and Visual Studio 2015 Community on the machine. 
Further more, when I open the same project in Visual Studio 2013 (with Web Essentials installed) I receive the same error. When I remove compilerconfig.json from the project the issue is still there. Only when I delete the compilerconfig.json file from the disk, I can successfully compile the project in Visual Studio 2013. 

The message I receive both in Visual Studio 2015 with WebCompiler extension installed and in Visual Studio 2013 with Web Essentials installed is:

1>------ Rebuild All started: Project: WebApplication1, Configuration: Debug Any CPU ------
1>  
1>  WebCompiler: Begin cleaning output of compilerconfig.json
1>  WebCompiler: Done cleaning output of compilerconfig.json
1>  
1>  WebCompiler: Begin compiling compilerconfig.json
1>  WebCompiler installing updated versions of the compilers...
1>C:\Users\UserA\Documents\Visual Studio 2015\Projects\WebApplication1\WebApplication1\Content\StyleSheet1.less : WebCompiler error 0: The system cannot find the path specified.
1>  WebCompiler: Done compiling compilerconfig.json
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

This behavior appeared in one of my projects. After that I tried to create new one and the issue is still there. Please note that the "missing" file exists on the specified location (I checked). 
The last thing I've tried is to start Visual Studio as admin and now everything worked fine! So, now the only trouble is that for WebCompiler admin mode is needed. From my end this is good enough, but I wanted to inform you about the issue, maybe this can give you a good insight.

**Comment by phillipsj** [comment]
I am receiving this same error when using Azure CI.

**Comment by madskristensen** [comment]
This is not related to Admin mode or not. It has to do with a missing file in 
`%localappdata%\temp\WebCompler1.xx`

Try deleting that folder and restart VS. The extension will then recreate the folder

**Comment by MCOTW** [comment]
I have deleted that folder as well as to try using Admin mode. Neither option fixes the error for me. Any other suggestions?

**Comment by robertjf** [comment]
@madskristensen I'm having a similar issue:

```
Unhandled Exception: System.IO.IOException: The process cannot access the file 'D:\Users\rfoster\AppData\Local\Temp\WebCompiler1.9.286' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at WebCompiler.CompilerService.Initialize() in C:\projects\webcompiler\src\WebCompiler\Compile\CompilerService.cs:line 86
   at WebCompiler.CompilerService.GetCompiler(Config config) in C:\projects\webcompiler\src\WebCompiler\Compile\CompilerService.cs:line 37
   at WebCompiler.ConfigFileProcessor.ProcessConfig(String baseFolder, Config config) in C:\projects\webcompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 147
   at WebCompiler.ConfigFileProcessor.Process(String configFile, IEnumerable`1 configs, Boolean force) in C:\projects\webcompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 44
   at WebCompiler.Program.Main(String[] args) in C:\projects\webcompiler\src\WebCompiler\Program.cs:line 27
Process terminated with code -532462766.
```

If I kill off the associated cmd task that's blocking access to the temp directory then I get this instead but the files are still not being generated:

```
Process terminated with code 0.
```
Also of note - the cmd task blocking the temp directory does not get stopped when VS2015 is closed - it'll remain running.  I've tried deleting the folder; killing off the task, but so far nothing's helped.  This is only recently become an issue in the past couple of weeks.

**Comment by robertjf** [comment]
@madskristensen this may be related to #164 - I suspect something like the following:
It seems that under some circumstances trying to run batch files via Process.Start is hanging (the batch file never gets executed even though the cmd is running in memory).

Note: I can't even compile a forked version of WebCompiler as the batch file in the pre-build event won't return (it hangs).

**Comment by robertjf** [comment]
oh, I'm running Windows 10 Build 11082 with latest Visual Studio 2015 Update 1 (tried a re-install of VS2015 to see if that would help - it didn't)

**Comment by Dominik321321** [comment]
Hi, Robertjf, i was in same issue, atlast i got the solution using  "Long Path Tool" , if you want you can try it. thanks

**Comment by muhengseow** [comment]
We had a similar issue on Windows 8.1 with VS 2015 Enterprise. We had to run prepare.cmd manually from C:\Users\<username>\AppData\Local\Temp\WebCompiler1.10.306.

**Comment by LuckyURE** [comment]
My system is locked down by system admins and I can't run exe files from the temp directly which Web Compiler requires.  How can I change Web Compiler so that it uses a specific directory?

**Comment by hmadrigal** [comment]
In my case the Antivirus and/or security polices from our domain does not allow apps to run freely when the're invoked from %APPDATA% (not sure if all apps but at least, WebCompiler was not allowed). 
I copied the binaries to a different path and then everything worked just fine.
Is there any chance to add a setting about where to copy the executable ? (It's not a big deal, but it may become handy)

**Comment by RogerPleijers** [comment]
We were having a similar issue. Initially we resolved it by using the solution described by muhengseow as shown above. Unfortunately the issue returned though, every time Visual Studio opened the WebCompiler folder was cleaned.

In the end we had to perform one additional step after running prepare.cmd, which was adding an empty log.txt file to the WebCompiler folder, after that everything worked fine again. 

We found out by examining the WebCompiler code in CompilerService.Initialize(), which only performs the initialization if either the node_modules folder, node.exe or log.txt were not found.

**Comment by CelsoP** [comment]
Besides the fact the subject is old I have got the same error and I solved it by giving full permission to my user at the temp folder. (C:\Users\_--username--_\AppData\Local\Temp).

**Comment by RichardPetheram** [comment]
The company I'm currently working for has locked down executables from all but a few paths by group policy. To get round this (with blessing of the sysadmin) I moved the WebCompiler1.xx folder to a permitted path, then created a soft link to the directory from its original Local\Temp location. Success! Group policy uses the actual path to the cmd files, but the extension references them from the soft link.

**Comment by mgandley** [comment]
@muhengseow, I was able to get this working with the exact same fix.  I wish I had seen your post earlier.  Linking post just in case it helps anyone else.

https://github.com/madskristensen/WebCompiler/issues/390#issuecomment-475427735

**Comment by dlynchcodes** [comment]
I've got a similar issue but my situation seems to be slightly different. The WebCompiler1.X folder gets recreated after deletion but the only contents is an empty log.txt file. This means that even if I move the folder around or anything like that, nothing will happen.

Anybody know why WebCompiler won't install properly for me?

**Comment by Rahmanism** [comment]
I still have this problem in Visual Studio 2019 16.7

**Comment by brettandrew** [comment]
Windows 11, Visual Studio 2019.

So managed to fix this, log off VS then delete all files in your local temp folder.

C:\Users\brett\AppData\Local\Temp

Yours will be in C:\Users\[%your username%]\AppData\Local\Temp

Restart VS and attempt to compile, works.

**Comment by awe-source** [comment]
dunno an easier way to figure this out but where I'am its becasue "prepare.cmd" cannot be run (applocker) and its a giant PITA.
options are run VS as admin (which for some reason is blocked from other things like web access and so can't sign into account for licence, for example) which probably bypasses the applocker things here.
anyway in windows event viewer, look for "applications and services logs > Microsoft > windows > applocker > msi and scripts" just after you "fail" to compile and if you see something like "......\temp\... \webcompiler...\prepare.cmd was prevented from running" then your hitting this wall...

it would be nice if the error message was a littel more obviious than "system couldnt find the path specified" but perhaps its a redherring error NOT referring to the webcompiler looking for a file, but that webcompile couldn't get he output from "prepare.cmd" or something...

the only solution Ive got is asking admin to exclude this from applocker, but its a big job keeping track of these exceptions (esp when teh path keeps changing (versions)) which is not super sustainable...
whatevers...

HTH

**Comment by jbress** [comment]
I had a similar issue :

In a .NET (Core) project, I'm using compilerconfig.json alongswith BuildWebCompiler2022 Nuget package, which uses WebCompiler 1.14.10 under the hood.
For an unknown reason, WebCompiler started to fail compiling my scss :
for every input scss file, I get "WebCompiler installing updated versions of the compilers..." and "**The system cannot find the path specified**".

**The following procedure fixed the issue :**

1 open WebCompiler.exe in a resource editor (dotPeek can be used aswell) :
WebCompiler.exe can be located in %UserProfile%\.nuget\packages\buildwebcompiler2022\1.14.10\tools\net4.8\

2 save the following resources to files :
WebCompiler.Node.node.7z
WebCompiler.Node.node_modules.7z

3 extract the content of these two 7z files in the WebCompiler temporary folder
example : %LocalAppData%\Temp\WebCompiler1.14.10

4 Et voilà !

By reflectoring WebCompiler.exe with dotPeek, I found that WebCompiler does these steps when it's being initialized ;
it looks for the existence of log.txt, node.exe and node_modules in the temp folder ;
if they don't exist, it does step 2 and 3 above (the equivalent of it, using 'prepare.cmd').
for an unknown reason, it's not able to do so on my machine anymore.

**Comment by Appli4Ever** [comment]
@jbress It worked. I hade this problem for months! I dont`t know if this affects anything but I had 2 WebCompiler folders in %LocalAppData%\Temp\ (two versions: 1.14.10 and 11). Just to be safe I extracted both 7z to both versions.

**Comment by mtanneryd** [comment]
I had this problem too and as it turned out it was caused by prepare.cmd failing to do its job when it tried to extract node.exe and node_modules to the %LocalAppData%\Temp\WebCompiler<version> folder. The reason being that the bundled 7z.exe failed to load the bundled 7z.dll. I have tried to figure out why it fails to do that but still hav not found out why.
