### ISSUE TITLE
Error when adding .babelrc

### ISSUE THREAD

**Issue by Saturn2888** [madskristensen/WebCompiler#181]
If I add a `.babelrc` file like this:

```json
{
    "plugins": ["transform-runtime"],
    "presets": ["es2015", "stage-0"]
}
```

I get this error in VisualStudio when saving an es6 file:

```
Severity    Code    Description Project File    Line    Suppression State
Error       ReferenceError: [BABEL] FILENAME.es6: Unknown option: .babelrc.presets
    at Logger.error (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
    at OptionManager.init (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Object.exports.transform (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel\lib\babel\util.js:40:22)
    at Object.exports.compile (C:\Users\USERNAME\AppData\Local\Temp\WebCompiler1.10.300\node_modules\babel\lib\babel\util.js:49:20)
    FILENAME    FILENAME.es6    0   
```

I tried adding some newer Babel dependencies to an npm package.json to see if that'd fix my issue:

```json
"dependencies": {
    "babel-core": "6.4.0",
    "babel-eslint": "5.0.0-beta6",
    "babel-plugin-transform-runtime": "6.4.3",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-stage-0": "6.3.13"
}
```

Didn't fix it.

Looks like the Babel version in WebCompiler is `5.8.x`, and I think the `.babelrc` file only works with `6.x.x`. This means I can't update the Babel version unless WebCompiler updates it correct?

**Comment by tonidy** [comment]
Any update on this issue? As I also want to use Babel 6.

**Comment by DoctaWorm** [comment]
It would be nice to have this added.

**Comment by alivingspirit** [comment]
+1

**Comment by daggmano** [comment]
Two years later, this is still an issue. Tried to 'hide' the babel config by placing it in package.json, but am getting 'Unknown option: \package.json.presets'.  Very frustrating.
