### ISSUE TITLE
scss compilation fails: Cannot find module 'async-foreach'

### ISSUE THREAD

**Issue by robertppn** [madskristensen/WebCompiler#252]
### Installed product versions
- Visual Studio: Enterprise 2015
- This extension: 1.11.319

### Description
After installing Webcompiler saving/compiling any *.scss file results in an error:

Error		module.js:338
    throw err;
          ^
Error: Cannot find module 'async-foreach'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Robert\AppData\Local\Temp\WebCompiler1.11.319\node_modules\node-sass\bin\node-sass:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by ngovanhuy** [comment]
you had answer for this question?

**Comment by robertppn** [comment]
no but it worked after some trail and error, try:
- remove extension
- delete all stuff from the AppData\Local\Temp\WebCompiler1.11.319 folder
- reinstall

**Comment by bandrus** [comment]
This solved my issue! Thank you so much!

**Comment by wieslawo** [comment]
This solved my problems, thans.

**Comment by sibabalwe47** [comment]
This solved my issue. Appreciate it.

**Comment by devjona** [comment]
I deleted the contents from `AppData\...\WebCompiler#.#...` and tried removing the extension. I don't use VS a lot, and didn't know how long it would take for the "scheduled" uninstall to be performed. I restarted VS and compiled, didn't have any issues this time.

Maybe simply deleting the folder contents helps? And a restart...

**Comment by amalgyte** [comment]
Removing the Webcomplier directory from the local users folder and building again works for me.
...\AppData\Local\Temp\WebCompiler1.12.405
Thanks for helping solve this.  Saved some time.

**Comment by MarcoMiltenburg** [comment]
Maybe helpfull for others, when you are using RDP this folder might be `..\AppData\Local\Temp\<number>\WebCompiler1.12.405` where `<number>` is a folder with just a number as it's name.

**Comment by monsieurberry** [comment]
Greetings from 2021. Still works!

Just spent 3 hours pondering this and could have spent many more had I not found this issue note.

@robertppn I could kiss you.
