### ISSUE TITLE
With latest update webcompiler is throwing error

### ISSUE THREAD

**Issue by Ilhom-S** [madskristensen/WebCompiler#272]
### Installed product versions
- Visual Studio: 2015 Pro

System.UnauthorizedAccessException: Access to the path '7z.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at WebCompiler.CompilerService.Initialize() in C:\---\webcompiler\src\WebCompiler\Compile\CompilerService.cs:line 86
   at WebCompilerVsix.WebCompilerInitPackage.<>c.<Initialize>b__2_3(Object o) in C:\---\webcompiler\src\WebCompilerVsix\WebCompilerPackage.cs:line 101

This is exception is giving when open visual studio without admin rights

**Comment by raver2046** [comment]
same problem

**Comment by gRoussac** [comment]
Hi, 

Run as admin I get 

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\groussac\AppData\Local\Temp\WebCompiler1.11.326\node_modules\tar' is denied.

```

Best regards
