### ISSUE TITLE
Exception raised in multi-project solution with web service

### ISSUE THREAD

**Issue by AccessIT** [madskristensen/WebCompiler#300]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.11.326

### Description
Exception showing in output window when building project. Build and project work fine

### Steps to recreate
Multi-project solution with one project being a web service
Select build or rebuild solution

### Current behavior
Shows in output window for "Web Compiler" - same exception hit twice, output is below

4/04/2017 1:07:53 PM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
4/04/2017 1:07:53 PM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227

### Expected behavior
No exception raised :)

**Comment by enginaar** [comment]
Same here. Cannot compile scss files.

9/6/2018 12:57:18 PM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
