### ISSUE TITLE
After initial file compile I get error: "There is an error in the compilerconfig.json file. This could be due to a change in the format after this extension was updated."

### ISSUE THREAD

**Issue by xevious99** [madskristensen/WebCompiler#344]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.4.0
- This extension: 1.1.375

### Project Information
- Target Framework: .NET Core 2.0
- Angular 4 (Microsoft.AspNetCore.SpaTemplates)

### Description
Compiling scss file results in a Web Compiler popup error "There is an error in the compilerconfig.json file. This could be due to a change in the format after this extension was updated.".

### Steps to recreate
1. Right click on .scss file and select Web Compiler -> Compile file and this is successfully creates a compilerconfig.json file with the input and output relative file locations.  It also creates the css and min.css files.
2. Modify the css with valid css and click save.   The popup as described in the Description appears.
The following is from the Web Compiler output:

11/6/2017 3:46:45 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at EnvDTE.SourceControl.IsItemUnderSCC(String ItemName)
   at WebCompilerVsix.ProjectHelpers.CheckFileOutOfSourceControl(String file) in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 30
   at WebCompilerVsix.CompilerService.<>c.<get_Processor>b__4_0(Object s, CompileFileEventArgs e) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 30
   at WebCompiler.ConfigFileProcessor.OnBeforeProcess(Config config, String baseFolder, Boolean containsChanges)
   at WebCompiler.ConfigFileProcessor.ProcessConfig(String baseFolder, Config config)
   at WebCompiler.ConfigFileProcessor.SourceFileChanged(String configFile, String sourceFile, String projectPath, HashSet`1 compiledFiles)
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 101

### Current behavior
An error occurs when either a change is made and you save or if you select Web Compiler -> Re-compile file.

### Expected behavior
There should be no errors and the css regular and min files should be generated successfully upon saving the .scss file or by Re-compiling the file.

**Comment by IvanYu1** [comment]
Hi @jeff-kissinger ,

Do you know how to resolve this issue? I am getting the same issue.
