### ISSUE TITLE
when click publish on web project Appears an error on show output from Web Compiler

### ISSUE THREAD

**Issue by mlorbetske** [madskristensen/WebCompiler#353]
From https://developercommunity.visualstudio.com/content/problem/183605/when-click-publish-on-web-project-appears-an-error.html

17-Jan-18 10:11:15: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
at EnvDTE80.DTE2.get_ActiveDocument()
at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
17-Jan-18 10:11:15: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
at EnvDTE80.DTE2.get_ActiveDocument()
at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227

**Comment by jphellemons** [comment]
I have exactly the same error:
````
7-2-2018 16:53:10: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
````
seems since the latest visual studio 2017 update? 15.5.6 or is it unrelated?

**Comment by thandley** [comment]
This is happening to me now. Same error
