### ISSUE TITLE
WebCompiler1.11.375\node_modules\node-sass\lib\binding.js:13: throw new Error(errors.unsupportedEnvironment());

### ISSUE THREAD

**Issue by ericwj** [madskristensen/WebCompiler#373]
### Installed product versions
- Visual Studio: 2017 Community 15.8.0 Preview 1.1
- This extension: 1.11.375
### Description
Unsupported environment

### Steps to recreate
1. Do something completely different
2. Have BuildWebCompiler installed
3. Rebuild a successfull build
4. Wait 5 minutes
5. Fail

### Current behavior
```
BuildWebCompiler 1.11.375
VS 15.8.0 Preview 1.1

.scss : WebCompiler error 0: C:\Users\Eric\AppData\Local\Temp\WebCompiler1.11.375\node_modules\node-sass\lib\binding.js:13
.scss : WebCompiler error 0:       throw new Error(errors.unsupportedEnvironment());
.scss : WebCompiler error 0:       ^
.scss : WebCompiler error 0: 
.scss : WebCompiler error 0: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (64)
.scss : WebCompiler error 0: For more information on which environments are supported please see:
.scss : WebCompiler error 0: https://github.com/sass/node-sass/releases/tag/v4.5.3
.scss : WebCompiler error 0:     at module.exports (C:\Users\Eric\AppData\Local\Temp\WebCompiler1.11.375\node_modules\node-sass\lib\binding.js:13:13)
.scss : WebCompiler error 0:     at Object.<anonymous> (C:\Users\Eric\AppData\Local\Temp\WebCompiler1.11.375\node_modules\node-sass\lib\index.js:14:35)
.scss : WebCompiler error 0:     at Module._compile (internal/modules/cjs/loader.js:678:30)
.scss : WebCompiler error 0:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
.scss : WebCompiler error 0:     at Module.load (internal/modules/cjs/loader.js:589:32)
.scss : WebCompiler error 0:     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
.scss : WebCompiler error 0:     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
.scss : WebCompiler error 0:     at Module.require (internal/modules/cjs/loader.js:626:17)
.scss : WebCompiler error 0:     at require (internal/modules/cjs/helpers.js:20:18)
.scss : WebCompiler error 0:     at Object.<anonymous> (C:\Users\Eric\AppData\Local\Temp\WebCompiler1.11.375\node_modules\node-sass\bin\node-sass:11:10)
```

### Expected behavior
Build. Successful. Fast.

**Comment by ericwj** [comment]
Worse yet, I left out the start of the build output wrt BuildWebCompiler:
```
1>WebCompiler: Begin compiling compilerconfig.json
1>WebCompiler installing updated versions of the compilers...
1>WebCompiler installing updated versions of the compilers...
1>	Compiled wwwroot/css/email.css
1>	Minified wwwroot/css/email.min.css
1>C:\Users\Eric\Source\Repos\BNI\src\BNI.RazorPages\wwwroot\css\bni.scss : WebCompiler error 0: C:\Users\Eric\AppData\Local\Temp\WebCompiler1.11.375\node_modules\node-sass\lib\binding.js:13
etc
```
It did it well literally seconds ago, failed only on the second .scss in the project.
