### ISSUE TITLE
Dotnet build fails - Value cannot be null. Parameter name: path1

### ISSUE THREAD

**Issue by Hashemalrifai** [madskristensen/WebCompiler#381]
### Installed product versions
- Windows OS.
- dotnet Core 2.1.401
- "BuildBundlerMinifier" Version="2.6.362"
- "BuildWebCompiler" Version="1.11.375"

### Description
Running `dotnet build` throws an error: 
`C:\xxx\.nuget\packages\buildwebcompiler\1.11.375\build\BuildWebCompiler.targets(12,9): error : Value cannot be null. [pathtoproject.csproj]
C:\xxx\.nuget\packages\buildwebcompiler\1.11.375\build\BuildWebCompiler.targets(12,9): error : Parameter name: path1 [pathtoproject.csproj]`

### Notes:
- But it still work when building using Visual Studio 2017, but I need to run it using dotnet CLI 
- Still fails when using `dotnet restore` before `build`
- Same error in two different environments.

**Comment by DanielPLungu** [comment]
I have 2 projects (dotnet core 2.1.301) in VSTS and both fail to build because of webcompiler.
Both have the same package version installed:
<PackageReference Include="BuildBundlerMinifier" Version="2.8.391" />
<PackageReference Include="BuildWebCompiler" Version="1.12.394" />

The first fails with message:
C:\xxx\.nuget\packages\buildwebcompiler\1.12.394\build\BuildWebCompiler.targets(12,9): error : Value cannot be null. [pathtoproject.csproj]
C:\xxx\.nuget\packages\buildwebcompiler\1.12.394\build\BuildWebCompiler.targets(12,9): error : Parameter name: path1 [pathtoproject.csproj]

The second fails with message:
C:\xxx\.nuget\packages\buildwebcompiler\1.12.394\build\BuildWebCompiler.targets(12,9): error : Could not load file or assembly 'NUglify, Version=1.5.12.0, Culture=neutral, PublicKeyToken=15bc7810aec21b5e'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [pathtoproject.csproj]

Both build and publish without error using Visual Studio 2017.

**Comment by TimurZanagar** [comment]
Hi folks,
I've got the same issue on my build server with .NET Core 2.2.105 and with BuildWebCompiler v1.12.394.

**Comment by physix99** [comment]
Hi,

I also had the same issue, my issue was because I was using an @import function with a list of files, I had commented one of them out, and that was making the file path invalid, therefore causing the above error.

e.g.

@import
   //'base/base',
    'base/typography';

The fix for me was to just remove that commented line, now it runs fine.

**Comment by sharpjs** [comment]
This is happening for me in 2025 when building using `dotnet.exe`.  The failure is intermittent, suggesting it is some sort of race condition.  Sometimes it works.  Sometimes it doesn't.  I've tried ensuring that Visual Studio is not running.  I've tried inserting a ten-second delay before the `WebCompile` task.

I wish I could get a stack trace.

```
13:05:44.587  29:7>Target "WebCompile: (TargetId:152)" in file "C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\build\BuildWebCompiler.targets" from project "D:\Code\{org}\{app}.2\{app}\{app}.csproj" (target "BeforeCompile" depends on it):
                   Assembly loaded during TaskRun: WebCompiler, Version=1.12.405.0, Culture=neutral, PublicKeyToken=null (location: C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\tools\netstandard2.0\WebCompiler.dll, MVID: 55fe3cba-1376-4cf2-a85b-24b485e39f4a, AssemblyLoadContext: MSBuild plugin C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\tools\netstandard2.0\WebCompiler.dll)
                   Using "WebCompiler.CompilerBuildTask" task from assembly "C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\build\..\tools\netstandard2.0\WebCompiler.dll".
                   Task "WebCompiler.CompilerBuildTask" (TaskId:96)
                     Task Parameter:FileName=D:\Code\{org}\{app}.2\{app}\compilerconfig.json (TaskId:96)

                     WebCompiler: Begin compiling compilerconfig.json (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (location: C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\tools\netstandard2.0\Newtonsoft.Json.dll, MVID: 5179dd1b-79f0-47d0-ac65-7ed8a725efc1, AssemblyLoadContext: MSBuild plugin C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\tools\netstandard2.0\WebCompiler.dll) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Runtime.Serialization.Primitives, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Runtime.Serialization.Primitives.dll, MVID: b4807c35-e08d-4387-a428-122655959b66, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.IO, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.IO.dll, MVID: d2dc067f-e71d-4d63-bc43-5f295de629db, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Globalization, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Globalization.dll, MVID: f88a81e7-9065-496a-878a-5f599b72b106, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Runtime.Extensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Runtime.Extensions.dll, MVID: a84ee38e-5370-44aa-b931-3458071e147a, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Dynamic.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Dynamic.Runtime.dll, MVID: fd493b67-ef03-4970-8f26-3801381462d2, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Reflection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Reflection.dll, MVID: 416d295f-9c68-4a30-9b88-d9c026f50d2a, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Reflection.Extensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Reflection.Extensions.dll, MVID: e7db987f-a438-4720-894d-733b9e678fe9, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Reflection.Emit.ILGeneration, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Reflection.Emit.ILGeneration.dll, MVID: 19075a8e-5c5f-4da1-8873-74a338a95a9c, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Reflection.Emit.Lightweight, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Reflection.Emit.Lightweight.dll, MVID: a03f3028-f78e-4ce6-a05e-257fd85426af, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): System.Reflection.Primitives, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.6\System.Reflection.Primitives.dll, MVID: 7516c76d-131b-4b10-b7ea-f8785d01bfcc, AssemblyLoadContext: Default) (TaskId:96)
                     Assembly loaded during TaskRun (WebCompiler.CompilerBuildTask): Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (location: , MVID: ceb3f82c-307d-4de0-b7e6-cb305e32a1b5, AssemblyLoadContext: Default) (TaskId:96)
13:05:44.702  29:7>C:\Users\Jeff\.nuget\packages\buildwebcompiler\1.12.405\build\BuildWebCompiler.targets(12,9): error : Value cannot be null. (Parameter 'path1') [D:\Code\{org}\{app}.2\{app}\{app}.csproj]
                   Done executing task "WebCompiler.CompilerBuildTask" -- FAILED. (TaskId:96)
```

**Comment by sharpjs** [comment]
Learned how to debug MSBuild.  Here's the stack trace.

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'path1')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ArgumentNullException.Throw(String paramName) in System\ArgumentNullException.cs:line 81
   at System.IO.Path.Combine(String path1, String path2) in System.IO\Path.cs:line 281
   at WebCompiler.SassDependencyResolver.UpdateFileDependencies(String path) in WebCompiler\SassDependencyResolver.cs:line 51
   at WebCompiler.DependencyResolverBase.GetDependencies(String projectRootPath) in WebCompiler\DependencyResolverBase.cs:line 30
   at WebCompiler.DependencyService.GetDependencies(String projectRootPath, String sourceFile) in WebCompiler\DependencyService.cs:line 39
   at WebCompiler.Config.HasDependenciesNewerThanOutput(FileInfo input, FileInfo output) in WebCompiler\Config.cs:line 65
   at WebCompiler.Config.CompilationRequired() in WebCompiler\Config.cs:line 60
   at WebCompiler.ConfigFileProcessor.Process(String configFile, IEnumerable`1 configs, Boolean force) in WebCompiler\ConfigFileProcessor.cs:line 43
   at WebCompiler.CompilerBuildTask.Execute() in WebCompiler\CompilerBuildTask.cs:line 58

  This exception was originally thrown at this call stack:
    System.ArgumentNullException.Throw(string) in ArgumentNullException.cs
    System.IO.Path.Combine(string, string) in Path.cs
    WebCompiler.SassDependencyResolver.UpdateFileDependencies(string) in SassDependencyResolver.cs
    WebCompiler.DependencyResolverBase.GetDependencies(string) in DependencyResolverBase.cs
    WebCompiler.DependencyService.GetDependencies(string, string) in DependencyService.cs
    WebCompiler.Config.HasDependenciesNewerThanOutput(System.IO.FileInfo, System.IO.FileInfo) in Config.cs
    WebCompiler.Config.CompilationRequired() in Config.cs
    WebCompiler.ConfigFileProcessor.Process(string, System.Collections.Generic.IEnumerable<WebCompiler.Config>, bool) in ConfigFileProcessor.cs
    WebCompiler.CompilerBuildTask.Execute() in CompilerBuildTask.cs
```

**Comment by sharpjs** [comment]
Cause found.  The regular expression [here](https://github.com/madskristensen/WebCompiler/blob/c01fbbf785ea16a9b8784b1697e3095c3ffd0596/src/WebCompiler/Dependencies/SassDependencyResolver.cs#L53) detects the word `@import` in a comment as the start of an import.  Proof:

![Image](https://github.com/user-attachments/assets/ef5673c0-d224-496f-9b1c-8c67649ee14a)
