### ISSUE TITLE
Compiling JS Files Error

### ISSUE THREAD

**Issue by MarkSky** [madskristensen/WebCompiler#409]
### Installed product versions
- Visual Studio: Visual Studio Community 2017 (15.9.7)
- This extension: 1.12.394

When I try to compile a js file, it doesn't work.
Add I got the error message:

> ReferenceError: [BABEL] D:/ShoppingCompany/wwwroot/js/datachange.js: 
> Unknown option: \.babelrc.presets
> at Logger.error (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
> at OptionManager.mergeOptions (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
> at OptionManager.addConfig (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
> at OptionManager.findConfigs (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
> at OptionManager.init (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
> at File.initOptions (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\index.js:147:75)
> at new File (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\file\index.js:137:22)
> at Pipeline.transform (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
> at Object.exports.transform (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel\lib\babel\util.js:40:22)
> at Object.exports.compile (C:\Users\XX\AppData\Local\Temp\WebCompiler1.12.394\node_modules\babel\lib\babel\util.js:49:20)ShoppingCompany	D:\ShoppingCompany\wwwroot\js\pointchange.js	0

**Comment by ashrafsabrym** [comment]
Old Babel 5.x used by WebCompiler [doesn't support presets](https://github.com/babel/website/blob/5.0.0/docs/usage/options.md)
