### ISSUE TITLE
Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by PeterPann23** [madskristensen/WebCompiler#461]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.12.394

### Description
when compiling a non web project the web compiler generates error messages
```
6/26/2020 10:39:34 AM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
6/26/2020 10:39:34 AM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
6/26/2020 10:39:36 AM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
6/26/2020 10:39:36 AM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
6/26/2020 10:39:36 AM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
6/26/2020 10:39:36 AM: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227
```

### Steps to recreate
1. Solution, 
2. Have class lib as well as web application
3. Publish lib as NuGet package

### Current behavior
Not sure why but sometimes I get 2 sometimes I get more errors depending on the lib in my solution

### Expected behavior
There clearly is an issue in ProjectHelpers.cs:line 227 that causes the error

**Comment by CZEMacLeod** [comment]
Get this a lot too. Is this extension still supported and being updated?

**Comment by GerardFR** [comment]
Same here. It appeared after I added a couple of projects to my solution.
