### ISSUE TITLE
Babel errors on compiling (minifying) js files

### ISSUE THREAD

**Issue by ElStupid** [madskristensen/WebCompiler#484]
### Installed product versions
- Visual Studio: 2022 Community Edition
- This extension: 1.14.1

### Description
Babel errors on compiling (minifying) js files. I have a VS2019 installation on the samen machine, which works just fine (with Mads' extension)

### Steps to recreate
1. any.js
2. set output to any.min.js
3. try to compile it

### Current behavior
It doesn't compile, instead give me an error: (copy)

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Couldn't find preset "react" relative to directory "C:/website/js"
    at C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-cli\lib\babel\util.js:50:22)
	MyProject	C:\website\js\pnlverlof.js	0	

### Expected behavior
Should compile correctly

**Comment by ElStupid** [comment]
Sorry, wrong Github, please remove! :(

**Comment by 3rror404** [comment]
I know this is old and closed, but can you remember how you resolved this issue @ElStupid ?

**Comment by ElStupid** [comment]
Long ago indeed :) I think I didn't do anything to close this issue and fix it. Alternatively I used Jason Moore's fork
https://marketplace.visualstudio.com/items?itemName=Failwyn.WebCompiler64 
Which works great but with some issues (always compiles .js with "use strict"). If the latter is not an issue for you, all should be fine

**Comment by 3rror404** [comment]
Thanks for coming back to me. Unfortunately I'm using vs 2019. Maybe it's time I finally upgraded :)

**Comment by ElStupid** [comment]
Uhm yeah, support for those extensions is daunting of course. I only use VS2019 for some SSIS components which aren't supported too well in VS2022
