### ISSUE TITLE
Error logged System.IO.IOException: The process cannot access the file '' because it is being used by another process.

### ISSUE THREAD

**Issue by markvantilburg** [madskristensen/WebCompiler#70]
Had this error logged in the output view. Maybe hide the entire trace for this error?

I removed the actual filename between the ''.

```
8/6/2015 3:23:56 PM: System.IO.IOException: The process cannot access the file 'c:\temp\file.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at WebCompiler.ConfigFileProcessor.ProcessConfig(String baseFolder, Config config)
   at WebCompiler.ConfigFileProcessor.Process(String configFile)
   at WebCompilerVsix.CompilerService.<>c__DisplayClass6_0.<Process>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 63
```

**Comment by madskristensen** [comment]
I'd rather fix the actual issue that caused this. How can I repro this?

**Comment by markvantilburg** [comment]
I have like 60 .less files in my solution. Was adding them to the .json file by right-clicking each file and select 'compile'. But there are also dependencies across those files (base files).
