### ISSUE TITLE
Error when using symbolic linked folder

### ISSUE THREAD

**Issue by patrickklug** [madskristensen/WebCompiler#84]
I have trouble using WebCompiler with a symbolic link folder. The first time I compile the scss file it works but any subsequent compile results in the following error:

```
20/08/2015 4:09:51 PM: Microsoft.Assumes+InternalErrorException: Unable to add project item "C:\code\scss-test\scss-test\linkedCSS\test.css": ADDRESULT_Cancel
   at Microsoft.Assumes.Fail(String message, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<EvaluateAddResultAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<AddItemAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass4_0.<<AddFromFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.ProjectSystem.ThreadHandlingMultithreaded.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFromFile(String fileName)
   at WebCompilerVsix.ProjectHelpers.AddNestedFile(String parentFile, String newFile) in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 145
```

I have prepared a very simple VS2015 project to showcase the issue. You can download it here:

https://www.dropbox.com/s/cvbhufy0g181x79/scss-test.zip?dl=0

To reproduce, just run the `_RUNMEASADMIN.bat` file as an Administrator first. Feel free to check the contents of that file.
```
REM execute as admin in the current directory
cd %~dp0
mklink /d linkedCSS target-folder

pause
```
This simply creates a symbolic link called linkedCSS which is required to reproduce the problem. The `cd %~dp0` is necessary because running as Admin will change the current directory to windows/system. This just reverts back to the project folder.

Any ideas how this could be solved?

**Comment by madskristensen** [comment]
There is now a try/catch around that code so this should be fixed. Can you please help verify that in the latest version?

**Comment by madskristensen** [comment]
So this is an error that is being shown in the output window only? Does the compilation work correctly?

**Comment by patrickklug** [comment]
Yes, this is shown under Output.

The compilation works some times, other times it seems that this problem stops a proper complication and I'm left with an outdated css.

I frequently get this error but not consistently. Usually saving the scss file manually a few times (Ctrl+S) will solve it.

**Comment by madskristensen** [comment]
And this reproduces in the latest version uploaded today as well?

**Comment by patrickklug** [comment]
let me check

**Comment by patrickklug** [comment]
behavior changed. now I get the error only on the first manual save on any included scss files. error does not seem to happen after any subsequent save, or when pressing F5.

**Comment by madskristensen** [comment]
I think it's the project system that is the issue and not symbolic links. What type of project are you seeing this in? ASP.NET 5, Cordova, or...?

**Comment by patrickklug** [comment]
W10 Universal App

**Comment by madskristensen** [comment]
Can I get you to install Extensibility Tools http://vsixgallery.com/extension/f8330d54-0469-43a7-8fc0-7f19febeb897/ and then right-click the project and select "Project Information...".

![projectinfo](https://cloud.githubusercontent.com/assets/1258877/9594448/f54465ce-500f-11e5-8d09-a611d2fb4088.png)

That should show you various info  about the project. I need the `Kind` guid if you would be so kind to paste it here.

**Comment by patrickklug** [comment]
I installed the extension but cannot see the Project Information... button. The extension definitely shows up as installed.

I included a test project in the original post, if you want to double check the type of project:

https://www.dropbox.com/s/cvbhufy0g181x79/scss-test.zip?dl=0

**Comment by madskristensen** [comment]
I think I fixed it. Can you please try the latest CI build and let me know if you can still repro the issue? http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by patrickklug** [comment]
still happens on 1.3.141

**Comment by madskristensen** [comment]
Damn. This is very strange...

**Comment by madskristensen** [comment]
This time I'm pretty sure it's fixed. The CI build is ready if you want to give it a try

**Comment by patrickklug** [comment]
sorry, still happening on 1.3.142.

**Comment by madskristensen** [comment]
Ok, do you get the exact same error in the output window? Are any of the files in mention under source control? I could reproduce the issue, but after my fixes I can't

**Comment by madskristensen** [comment]
Also, is the compilerconfig.json file being created correctly if it doesn't exist?

**Comment by patrickklug** [comment]
same error but I just noticed that it is indeed fixed in the test project. Unfortunately not in my real project. Is there a way to get the 'kind' gui without your before mentioned add-in working?

**Comment by patrickklug** [comment]
I thought both are just a W10 Universal App but maybe there are some minor differences.

**Comment by madskristensen** [comment]
I fixed the Extensibility Tools to work correctly on non .csproj based project types. Get it here http://vsixgallery.com/extension/f8330d54-0469-43a7-8fc0-7f19febeb897/

**Comment by madskristensen** [comment]
If you can just paste the entire content of the file that opens when you select "Show Project Information", then that would be great

**Comment by patrickklug** [comment]
only removed the project name and path info.
```
Name:			 REMOVED
UniqueName:		 REMOVED.jsproj
FullName:		 C:\REMOVED\REMOVED\REMOVED.jsproj
FileName:		 C:\REMOVED\REMOVED\REMOVED.jsproj
Kind:			 {262852C6-CD72-467D-83FE-5EEB1973A190}

Properties:
	AddItemTemplatesGuid           	:	<no value>
	AllowLocalNetworkLoopback      	:	True
	AppxPackageRecipe              	:	C:\REMOVED\REMOVED\bin\Debug\REMOVED.build.appxrecipe
	AssemblySearchPaths            	:	
      {CandidateAssemblyFiles};
      ;
      {HintPathFromItem};
      {TargetFrameworkDirectory};
      {Registry:Software\Microsoft\,,AssemblyFoldersEx};
      {AssemblyFolders};
      {GAC};
      {RawFileName};
      bin\Debug\
    
	AutoRefresh                    	:	<no value>
	AvailablePlatforms             	:	System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]
	DebuggerSymbolsPath            	:	<no value>
	DefaultContentType             	:	Default
	DefaultLanguage                	:	en-US
	DefaultReferenceGroup          	:	<no value>
	DisableFastUpToDateCheck       	:	<no value>
	FinalAppxManifestName          	:	C:\REMOVED\REMOVED\bin\Debug\AppxManifest.xml
	FullPath                       	:	C:\REMOVED\REMOVED\REMOVED.jsproj
	IgnoreLocalNetworkLoopback     	:	<no value>
	IntermediateOutputPath         	:	bld\Debug\
	LayoutDir                      	:	C:\REMOVED\REMOVED\bin\Debug\AppX
	MinimumVisualStudioVersion     	:	.
	OutputPath                     	:	bin\Debug\
	OutputType                     	:	<no value>
	PackageAction                  	:	_GenerateAppxPackage
	ProjectGuid                    	:	34ff065e-db94-4512-98de-cc0576b8e00e
	ProjectPriFullPath             	:	C:\REMOVED\REMOVED\bin\Debug\ReverseMap\resources.pri
	ReferenceCachePath             	:	C:\Users\Patrick\AppData\Local\Temp\hzb215en_REMOVED_refcache
	RootNamespace                  	:	<no value>
	SDKIdentifier                  	:	Windows
	SDKReferenceDirectoryRoot      	:	C:\Users\Patrick\AppData\Local\Microsoft SDKs;C:\Program Files (x86)\Microsoft SDKs
	SDKReferenceRegistryRoot       	:	Software\Microsoft\Microsoft SDKs
	SDKVersion                     	:	10.0
	ShowAllFiles                   	:	<no value>
	SuppressOutOfDateMessageOnBuild	:	True
	TargetFrameworkIdentifier      	:	<no value>
	TargetFrameworkProfile         	:	<no value>
	TargetFrameworkVersion         	:	<no value>
	TargetPath                     	:	C:\REMOVED\REMOVED\bin\Debug\REMOVED
	TargetPlatformIdentifier       	:	UAP
	TargetPlatformVersion          	:	10.0.10240.0
	TargetPlatformWinMDLocation    	:	C:\Program Files (x86)\Windows Kits\10\References\CommonConfiguration\Neutral
	TargetRuntime                  	:	AppHost
	VisualStudioVersion            	:	14.0
	WindowsAppContainer            	:	True
	WinRTReferenceTabs             	:	TAB_SDK_EXTENSIONS
```

**Comment by madskristensen** [comment]
Ahh, the difference is that you have a universal windows 10 app and the test project you sent me was a windows 8.1 store app project

**Comment by patrickklug** [comment]
oops, my apologies. I thought I picked the same type.

**Comment by madskristensen** [comment]
No worries. I'm installing the Universal Apps stuff now

**Comment by madskristensen** [comment]
Universal Windows Apps works fine for me with the latest tooling installed. However, I get a different set of properties when I click Show Project Properties

**Comment by patrickklug** [comment]
Well, AFAIK, my project is just a normal W10 universal app but then again, I do not have the best experience with VS2015 so far. Lot's of hiccups.

**Comment by madskristensen** [comment]
Here's what I get from the Blank Universal Windows App template:

```
Name:			 UniversalWindowsApp1
UniqueName:		 UniversalWindowsApp1\UniversalWindowsApp1.csproj
FullName:		 REMOVED\UniversalWindowsApp1.csproj
FileName:		 REMOVED\UniversalWindowsApp1.csproj
Kind:			 {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}

Properties:
	ApplicationIcon                	:	<no value>
	ApplicationManifest            	:	DefaultManifest
	AssemblyFileVersion            	:	1.0.0.0
	AssemblyGuid                   	:	<no value>
	AssemblyKeyContainerName       	:	<no value>
	AssemblyKeyProviderName        	:	<no value>
	AssemblyName                   	:	UniversalWindowsApp1
	AssemblyOriginatorKeyFile      	:	<no value>
	AssemblyOriginatorKeyFileType  	:	1
	AssemblyOriginatorKeyMode      	:	0
	AssemblyType                   	:	0
	AssemblyVersion                	:	1.0.0.0
	Company                        	:	<no value>
	ComVisible                     	:	False
	Copyright                      	:	Copyright ©  2015
	DebugSecurityZoneURL           	:	<no value>
	DefaultClientScript            	:	0
	DefaultHTMLPageLayout          	:	1
	DefaultNamespace               	:	UniversalWindowsApp1
	DefaultTargetSchema            	:	1
	DelaySign                      	:	False
	Description                    	:	<no value>
	EnableSecurityDebugging        	:	True
	ExcludedPermissions            	:	<no value>
	FileName                       	:	UniversalWindowsApp1.csproj
	FullPath                       	:	REMOVED\UniversalWindowsApp1\
	GenerateManifests              	:	False
	LinkRepair                     	:	False
	LocalPath                      	:	REMOVED\UniversalWindowsApp1\
	ManifestCertificateThumbprint  	:	<no value>
	ManifestKeyFile                	:	<no value>
	ManifestTimestampUrl           	:	<no value>
	NeutralResourcesLanguage       	:	<no value>
	OptionCompare                  	:	0
	OptionExplicit                 	:	1
	OptionStrict                   	:	0
	OutputFileName                 	:	UniversalWindowsApp1.exe
	OutputType                     	:	1
	OutputTypeEx                   	:	4
	PostBuildEvent                 	:	<no value>
	PreBuildEvent                  	:	<no value>
	Product                        	:	UniversalWindowsApp1
	Project.TargetDescriptions     	:	Universal Windows
	Project.TargetFrameworkMonikers	:	
	Project.TargetPlatformMonikers 	:	
	ProjectType                    	:	0
	Publish                        	:	<Array of COM objects>
	ReferencePath                  	:	<no value>
	RootNamespace                  	:	UniversalWindowsApp1
	RunPostBuildEvent              	:	1
	SignAssembly                   	:	False
	SignManifests                  	:	False
	StartupObject                  	:	<no value>
	TargetFramework                	:	327680
	TargetFrameworkMoniker         	:	.NETCore,Version=v5.0
	TargetZone                     	:	<no value>
	Title                          	:	UniversalWindowsApp1
	Trademark                      	:	<no value>
	TypeComplianceDiagnostics      	:	False
	UAP.TargetPlatformMinVersion   	:	10.0.10240.0
	UAP.TargetPlatformVersion      	:	10.0.10240.0
	URL                            	:	REMOVED\UniversalWindowsApp1\
	Win32ResourceFile              	:	<no value>
```

**Comment by madskristensen** [comment]
Silly me, I created a C# project instead of a JavaScript project...

**Comment by madskristensen** [comment]
Success. I can repro consistently. Fix on its way

**Comment by patrickklug** [comment]
great. thanks!

**Comment by madskristensen** [comment]
I've removed the errors and it compiles ok now. I still haven't gotten the right experience completely locked down yet though. The Universal App project system is behaving very weird compared to the other project systems. I'll have to dig into this further, but at least now you should be unblocked

**Comment by patrickklug** [comment]
not sure if the fix is live but latest version (1.3.143) still has the issue for me.

**Comment by madskristensen** [comment]
I've raised the issue with the VS team that owns the Windows Store Apps project system. It appears to be an issue with that.

**Comment by patrickklug** [comment]
Thanks @madskristensen . Much appreciated.
